### ISSUE TITLE
Wait time Train and Wait time Backtest correlation

### ISSUE THREAD

**Issue by oakniiv** [zoome0215/predictBO#7]
What effect does training AI on 5min wait time have on backtesting it with 10 min wait time. Is wait time while training important? Because when backtesting and trading we can change it to whatever we want, should it be the same number?

**Comment by zoome0215** [comment]
I have no idea. One of the main objective of this open source project is to figure out exactly what is important.

My personal thought is that 5min/10min wait time doesn't really matter since you have trend for some interval (say 20 seconds~1 min), and after that, no longer how much time you wait, you will be in a window with different trend, so as long as the wait time is longer than the interval which a trend lasts, actual number, I think, doesn't matter.

I think I should write a code which analyses how much time a trend lasts in average.

**Comment by zoome0215** [comment]
I added a program as I said at the last sentence of the previous comment.
It seems that down trend lasts longer than upward trends by factor of 10 and downward trend lasts nearly as long as resting (not doing anything).

**Comment by zoome0215** [comment]
I will keep this question open if someone has some ideas about the correlations of those variables to learning time and accuracy.

**Comment by oakniiv** [comment]
Also the size of the data makes no sense, why does it matter if I train 1
month or two months.
If I train 2 months of data and backtest it with 90% winrate or train 1
month of data and get 90% winrate and then proceed with real trading the
results should be the same.
The AI should not only predict the direction but pick the perfect entry
time too.

On Feb 10, 2018 12:58 PM, "Tom" <notifications@github.com> wrote:

I will keep this question open if someone has some ideas about the
correlations of those variables to learning time and accuracy.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zoome0215/predictBO/issues/7#issuecomment-364646626>,
or mute the thread

**Comment by zoome0215** [comment]
Well, I thought, in modern economics, there are several trends with different time scales due to various factors (see [Business cycle](https://en.wikipedia.org/wiki/Business_cycle)).
 
I use much data as I can to make it learn as much scenarios as possible.
